---
# ansible_python_interpreter: /usr/bin/python3

ansible_restart_server: false
ansible_10periodic_path: /etc/apt/apt.conf.d/10periodic

ansible_install_packages:
  - unattended-upgrades
  - python-apt

ansible_blacllist_packages: []
  # - docker-ce
  # - mysql
  # - apache2

ansible_unhold_packages: []
  # - docker-ce
  # - mysql
  # - apache2
     
ansible_check_services: 
  # - apache2
  # - mysql
  # - docker


unattended_package_blacklist: []
unattended_autofix_interrupted_dpkg: true
unattended_minimal_steps: false
unattended_install_on_shutdown: false
unattended_mail: false
unattended_mail_only_on_error: false
unattended_remove_unused_dependencies: false
unattended_automatic_reboot: false
unattended_automatic_reboot_time: false
unattended_ignore_apps_require_restart: false

unattended_allowed_origins:
  - "${distro_id}:${distro_codename}"
  - "${distro_id}:${distro_codename}-security"

#Auto upgrade cconfigration variables
unattended_update_package_list: 1
unattended_download_upgradeable: 7
unattended_autoclean_interval: 7
unattended_dpkg_options: []
